### ISSUE TITLE
Webmin add rules into firewall

### ISSUE THREAD

**Issue by hunterpl** [TeamSpeak-Systems/ts3init_linux_netfilter_module#13]
Hello could someone help me how to configure what rules to add into webmin firewall with ts3 netfilter?

[recommended] Disable connection tracking with the help of raw table
Create ipset: ts3_authorized with a timeout of 30 seconds
If a source ip address is in the ipset ts3_authorized, renew the entry in the set to update the timeout then accept the packet.
Use ts3init_get_cookie matches to get connection requests and reply with TS3INIT_SET_COOKIE.
Use ts3init_get_puzzle matches to get the cookie replies from the client. If they match, add the source ip address to the ts3_authorizing ipset and then reply with TS3INIT_RESET
Drop all other packets

**Comment by nwerensteijn** [comment]
There are example scripts in the examples directory. Note that these are examples. For example I already heard from other people they use "recent" matches instead of "ipset". Also, if you are going to use ipset, please create them with enough buckets. The default is 1024. It should be at least the slot count configured on your server.

As for webmin, I doubt you can get a tool like that (a firewall web gui) to use a custom module. I did read here http://www.webmin.com/firewall.html that you can just ssh into the system. From there you can either use the examples directly, or add them into /etc/sysconfig/iptables or /var/lib/iptables.

**Comment by nwerensteijn** [comment]
Closing this issue due to lack of response
